# Site settings
title: lia bogoev
email: lbogoev@mit.edu
description: > # this means to ignore newlines until "baseurl:"
  The personal blog and portfolio of Lia Bogoev.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://liabogoev.com" # the base hostname & protocol for your site
twitter_username: elbowgo
github_username:  bogoli

# Build settings
markdown: kramdown

# Pagination
paginate: 2
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  design:
    output: true
    permalink: /design/:path/



